export const ROUTES = {
  HOME: '/',
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  PRODUCTS: '/products',
  MEN: '/products/men',
  WOMEN: '/products/women',
  NEW: '/products/new',
  COLLECTIONS: '/products/collections',
  PROFILE: '/profile',
  WISHLIST: '/profile/wishlist',
  CART: '/cart',
  CHECKOUT: '/cart/checkout',
  PAYMENT: '/cart/checkout/payment',
  PAYMENT_SUCCESS: '/cart/checkout/payment/success',
  ABOUT: '/about',
  CONTACT: '/about/contacts',
  REVIEWS: '/about/reviews',
  FAQ: '/about/faq',
  DELIVERY: '/about/delivery',

  // API ENDPOINTS
  GET_CART: '/api/cart',
  POST_LOCAL_CART: '/api/local-cart',
  POST_CART_ADD: '/api/cart/add',
  DELETE_CART_ITEM: '/api/cart/delete',
  POST_CART_MIGRATE: '/api/cart/migrate',
  PATCH_CART_QUANT: '/api/cart/update',
  DELETE_CART_CLEAR: '/api/cart/clear',
  GET_USER: '/api/user',
  GET_ORDERS_ARCHIVE: '/api/user/orders/archive',
  GET_ORDERS_ACTIVE: '/api/user/orders/active',
  GET_WISHLIST: '/api/wishlist',
  POST_WISHLIST_ADD: '/api/wishlist/add',
  DELETE_WISHLIST_ITEM: '/api/wishlist/remove',
  POST_LOCAL_WISHLIST: '/api/wishlist/local',
  POST_WISHLIST_MIGRATE: '/api/wishlist/migrate',
  GET_REVIEWS: '/api/review',
  POST_REVIEWS_ADD: '/api/review/add',
  GET_PRODUCTS_TYPE: '/api/products/type',
  GET_PRODUCTS_COLLECTION: '/api/products/collection',
  GET_PRODUCTS_TYPE_MEN: '/api/products/men/type',
  GET_PRODUCTS_COLLECTION_MEN: '/api/products/men/collection',
  GET_PRODUCTS_TYPE_WOMEN: '/api/products/women/type',
  GET_PRODUCTS_COLLECTION_WOMEN: '/api/products/women/collection',
  GET_SEARCH: '/api/search',
}
