export const ROUTES = {
  HOME: '/',
  SIGNIN: '/sign-in',
  SIGNUP: '/sign-up',
  PRODUCTS: '/products',
  MEN: '/products/men',
  WOMEN: '/products/women',
  NEW: '/products/new',
  MEN_NEW: '/products/men/new',
  WOMEN_NEW: '/products/women/new',
  SALE: '/products/sale',
  MEN_SALE: '/products/men/sale',
  WOMEN_SALE: '/products/men/sale',
  MEN_T_SHIRT: '/products/men/t-shirt',
  MEN_HOODIES: '/products/men/hoodies-sweatshirts',
  MEN_JACKETS: '/products/men/jackets',
  MEN_JEANS: '/products/men/jeans',
  WOMEN_DRESSES: '/products/women/dresses',
  WOMEN_TOPS: '/products/women/tops-t-shirt',
  WOMEN_BLOUSES: '/products/women/blouses-shirts',
  WOMEN_JEANS: '/products/women/jeans-pants',
  COLLECTIONS: '/products/collections',
  PROFILE: '/profile',
  WISHLIST: '/profile/wishlist',
  CART: '/cart',
  CHECKOUT: '/cart/checkout',
  PAYMENT: '/cart/checkout/payment',
  PAYMENT_SUCCESS: '/cart/checkout/payment/success',
  ABOUT: '/about',
  CONTACT: '/about/contacts',
  REVIEWS: '/about/reviews',
  FAQ: '/about/faq',
  DELIVERY: '/about/delivery',

  // API ENDPOINTS
  GET_CART: '/api/cart',
  POST_LOCAL_CART: '/api/local-cart',
  POST_CART_ADD: '/api/cart/add',
  DELETE_CART_ITEM: '/api/cart/delete',
  POST_CART_MIGRATE: '/api/cart/migrate',
  PATCH_CART_QUANT: '/api/cart/update',
  DELETE_CART_CLEAR: '/api/cart/clear',
  GET_USER: 'api/user',
}
